# Generated by Django 3.0.3 on 2020-06-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN13', models.CharField(max_length=13)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('pages', models.IntegerField()),
                ('cover_image', models.ImageField(upload_to='Books/Images')),
                ('languague', models.CharField(max_length=20)),
            ],
        ),
    ]
