# Generated by Django 3.0.3 on 2020-06-21 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN13',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BookStationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Station', models.IntegerField()),
                ('ISBN13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.Book')),
            ],
        ),
    ]
