# Generated by Django 3.0.3 on 2020-06-22 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Books', '0002_auto_20200621_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookstationrelation',
            old_name='Station',
            new_name='station',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.IntegerField()),
                ('ISBN13', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
