# Generated by Django 3.0.3 on 2020-07-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_auto_20200713_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='Users/Images/'),
        ),
    ]
