# Generated by Django 3.0.3 on 2020-07-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_auto_20200715_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='gener',
            field=models.CharField(choices=[('Open Source', 'Open Source'), ('Mobile', 'Mobile'), ('Java', 'Java'), ('Software Engineering', 'Software Engineering'), ('Internet', 'Internet'), ('Web Development', 'Web Development'), ('Miscellaneous', 'Miscellaneous'), ('Microsoft .NET', 'Microsoft .NET'), ('Object-Oriented Programming', 'Object-Oriented Programming'), ('Networking', 'Networking'), ('Theory', 'Theory'), ('Programming', 'Programming'), ('Python', 'Python'), ('PowerBuilder', 'PowerBuilder'), ('Computer Graphics', 'Computer Graphics'), ('Mobile Technology', 'Mobile Technology'), ('Business', 'Business'), ('Microsoft', 'Microsoft'), ('P', 'P'), ('XML', 'XML'), ('Perl', 'Perl'), ('Client-Server', 'Client-Server')], default='', max_length=100),
        ),
    ]
