# Generated by Django 3.0.3 on 2020-07-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0010_auto_20200716_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='imageURL',
            field=models.URLField(blank=True),
        ),
    ]
