# Generated by Django 3.0.3 on 2020-07-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0012_auto_20200716_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookstationrelation',
            old_name='ISBN13',
            new_name='book',
        ),
    ]
