# Generated by Django 3.0.3 on 2020-07-19 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0014_auto_20200719_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('default_station', models.CharField(choices=[('Tel Aviv - Savidor Center', 'Tel Aviv - Savidor Center'), ('Tel Aviv - University', 'Tel Aviv - University'), ('Tel Aviv - Ha-Shalom', 'Tel Aviv - Ha-Shalom'), ('Tel Aviv - Ha-Hagana', 'Tel Aviv - Ha-Hagana'), ('Nahariya', 'Nahariya'), ('Akko', 'Akko'), ('Karmiel', 'Karmiel'), ('Ahihod', 'Ahihod'), ('Kiryat Motskin', 'Kiryat Motskin'), ('Kiryat Haim', 'Kiryat Haim'), ('Haifa - Hutsot HaMifrats', 'Haifa - Hutsot HaMifrats'), ('Haifa - Merkazit HaMifrats', 'Haifa - Merkazit HaMifrats'), ('Haifa - Merkaz Hashmuna', 'Haifa - Merkaz Hashmuna'), ('Haifa - Bat Galim', 'Haifa - Bat Galim'), ('Haifa - Hof Hakarmel', 'Haifa - Hof Hakarmel'), ('Beit Sheaan', 'Beit Sheaan'), ('Afula', 'Afula'), ('Migdal HaEmek', 'Migdal HaEmek'), ('Yofneaam', 'Yofneaam'), ('Atlit', 'Atlit'), ('Binayamina', 'Binayamina'), ('Keysaria - Pardes Hana', 'Keysaria - Pardes Hana'), ('Hedera West', 'Hedera West'), ('Netanya', 'Netanya'), ('Netanya - Sapir', 'Netanya - Sapir'), ('Beit Yehushua', 'Beit Yehushua'), ('Herzliya', 'Herzliya'), ('Petah Tikva - Kiryat Arye', 'Petah Tikva - Kiryat Arye'), ('Petah Tikva - Sgula', 'Petah Tikva - Sgula'), ('Rosh HaAin North', 'Rosh HaAin North'), ('Kfar Saba - Nordaoo', 'Kfar Saba - Nordaoo'), ('Hod HaSharon - Sokolov', 'Hod HaSharon - Sokolov'), ('Raanana South', 'Raanana South'), ('Airport Ben Gurion', 'Airport Ben Gurion'), ("Modi'in outskirts", "Modi'in outskirts"), ("Modi'in Center", "Modi'in Center"), ('Jerusalem - Yizhak Navon', 'Jerusalem - Yizhak Navon'), ('Kfar Habad', 'Kfar Habad'), ('Lud - Ganei Aviv', 'Lud - Ganei Aviv'), ('Lud/Ramla', 'Lud/Ramla'), ('Beit Shemesh', 'Beit Shemesh'), ('Jesrualem - Tanahi Zoo', 'Jesrualem - Tanahi Zoo'), ('Jerusalem - Malha', 'Jerusalem - Malha'), ('Mazkeret Batia', 'Mazkeret Batia'), ('Kiryat Malachi - Yoav', 'Kiryat Malachi - Yoav'), ('Kiryat Gat', 'Kiryat Gat'), ("Lehavim/Raha'at", "Lehavim/Raha'at"), ("Be'er Sheva North - University", "Be'er Sheva North - University"), ("Be'er Sheva Center", "Be'er Sheva Center"), ('Dimona', 'Dimona'), ('Ofakim', 'Ofakim'), ('Netivot', 'Netivot'), ('Sderot', 'Sderot'), ('Ashkelon', 'Ashkelon'), ('Asdod - Ad Halom', 'Asdod - Ad Halom'), ('Yavne - West', 'Yavne - West'), ('Yavne - East', 'Yavne - East'), ("Be'er Yakov", "Be'er Yakov"), ('Rishon Letsiyon - HaRishonim', 'Rishon Letsiyon - HaRishonim'), ('Rishon Letsiyon - Moshe Dayan', 'Rishon Letsiyon - Moshe Dayan'), ('Bat Yam - HaKomemiyut', 'Bat Yam - HaKomemiyut'), ('Bat Yam - Yoseftal', 'Bat Yam - Yoseftal'), ('Holon Junction', 'Holon Junction')], default='Tel Aviv - Savidor Center', max_length=100)),
            ],
        ),
    ]
