# Generated by Django 3.0.3 on 2020-07-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0016_auto_20200719_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
