# Generated by Django 3.0.3 on 2020-07-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0017_auto_20200719_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstationrelation',
            name='station',
            field=models.CharField(choices=[('Tel Aviv - Savidor Center', 'Tel Aviv - Savidor Center'), ('Tel Aviv - University', 'Tel Aviv - University'), ('Tel Aviv - Ha-Shalom', 'Tel Aviv - Ha-Shalom'), ('Tel Aviv - Ha-Hagana', 'Tel Aviv - Ha-Hagana'), ('Haifa - Merkazit HaMifrats', 'Haifa - Merkazit HaMifrats'), ('Haifa - Merkaz Hashmuna', 'Haifa - Merkaz Hashmuna'), ('Haifa - Bat Galim', 'Haifa - Bat Galim'), ('Haifa - Hof Hakarmel', 'Haifa - Hof Hakarmel'), ('Netanya', 'Netanya'), ('Herzliya', 'Herzliya')], default='Tel Aviv - Savidor Center', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='default_station',
            field=models.CharField(choices=[('Tel Aviv - Savidor Center', 'Tel Aviv - Savidor Center'), ('Tel Aviv - University', 'Tel Aviv - University'), ('Tel Aviv - Ha-Shalom', 'Tel Aviv - Ha-Shalom'), ('Tel Aviv - Ha-Hagana', 'Tel Aviv - Ha-Hagana'), ('Haifa - Merkazit HaMifrats', 'Haifa - Merkazit HaMifrats'), ('Haifa - Merkaz Hashmuna', 'Haifa - Merkaz Hashmuna'), ('Haifa - Bat Galim', 'Haifa - Bat Galim'), ('Haifa - Hof Hakarmel', 'Haifa - Hof Hakarmel'), ('Netanya', 'Netanya'), ('Herzliya', 'Herzliya')], default='Tel Aviv - Savidor Center', max_length=100),
        ),
    ]
