# Generated by Django 3.0.3 on 2020-07-19 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0018_auto_20200719_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributions',
            name='station',
            field=models.CharField(choices=[('Tel Aviv - Savidor Center', 'Tel Aviv - Savidor Center'), ('Tel Aviv - University', 'Tel Aviv - University'), ('Tel Aviv - Ha-Shalom', 'Tel Aviv - Ha-Shalom'), ('Tel Aviv - Ha-Hagana', 'Tel Aviv - Ha-Hagana'), ('Haifa - Merkazit HaMifrats', 'Haifa - Merkazit HaMifrats'), ('Haifa - Merkaz Hashmuna', 'Haifa - Merkaz Hashmuna'), ('Haifa - Bat Galim', 'Haifa - Bat Galim'), ('Haifa - Hof Hakarmel', 'Haifa - Hof Hakarmel'), ('Netanya', 'Netanya'), ('Herzliya', 'Herzliya')], default='Tel Aviv - Savidor Center', max_length=100),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Books.Profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='station',
            field=models.CharField(choices=[('Tel Aviv - Savidor Center', 'Tel Aviv - Savidor Center'), ('Tel Aviv - University', 'Tel Aviv - University'), ('Tel Aviv - Ha-Shalom', 'Tel Aviv - Ha-Shalom'), ('Tel Aviv - Ha-Hagana', 'Tel Aviv - Ha-Hagana'), ('Haifa - Merkazit HaMifrats', 'Haifa - Merkazit HaMifrats'), ('Haifa - Merkaz Hashmuna', 'Haifa - Merkaz Hashmuna'), ('Haifa - Bat Galim', 'Haifa - Bat Galim'), ('Haifa - Hof Hakarmel', 'Haifa - Hof Hakarmel'), ('Netanya', 'Netanya'), ('Herzliya', 'Herzliya')], default='Tel Aviv - Savidor Center', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.Profile'),
        ),
    ]
